export const ADD_ARTIST = 'ADD_ARTIST';
export const REMOVE_ARTIST = 'REMOVE_ARTIST';
export const ADD_ARTIST_TO_MODAL = 'ADD_ARTIST_TO_MODAL';
export const REMOVE_ARTIST_FROM_MODAL = 'REMOVE_ARTIST_FROM_MODAL';